version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: code-advisor-db
    environment:
      POSTGRES_DB: code_advisor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - advisor-network

  # Code Advisor Agent API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-advisor-api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/code_advisor
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - advisor-network

  # PgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: code-advisor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@codeadvisor.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - advisor-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local

networks:
  advisor-network:
    driver: bridge
